[package]
name = "py-lzokay"
version = "2.0.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/henriquegemignani/py-lzokay"

[lib]
name = "lzokay"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.26.0", features = ["abi3-py310"] }
lzokay = "2.0.1"
